### ISSUE TITLE
[ALL] Environment Setting

### ISSUE THREAD

**Issue by roby238** [Intel-Edge-AI-SW-Developers-2nd-Team-1/BoardMaestro#6]
1. IDE Setting
- Done / In progress / To do
- Details:

2. Git clone or fork repository
- Done / In progress / To do
- Details: 

3. Make workspace
- Done / In progress / To do
- Details:

**Comment by roby238** [comment]
1. IDE Setting
- Done
- Details: pycharm, visual code

2. Git clone or fork repository
- Done
- Details: Git clone and fork repository

3. Make workspace
- Done
- Details: Expression_Calculating

**Comment by User3198352** [comment]
1. IDE Setting
- Done
- Details: pycharm

2. Git clone or fork repository
- Done
- Details: Git clone and fork repository

3. Make workspace
- Done
- Details: Hand_Pose_Estimation
